apiVersion: zone.micgoe.io/v1alpha1
kind: Zone
metadata:
  annotations:
    meta.upbound.io/example-id: zone/v1alpha1/zone
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    description: my terraform test cloud zone
    name: tf-vra-zone
    regionId: ${data.vra_region.this.id}
    tags:
    - key: my-tf-key
      value: my-tf-value
    - key: tf-foo
      value: tf-bar
