// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BlueprintInitParameters struct {

	// Blueprint YAML content.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// Human-friendly description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Human-friendly name used as an identifier in APIs that support this option.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of project that entity belongs to.
	// +crossplane:generate:reference:type=github.com/micgoe/provider-vmware-vra/apis/project/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// Flag to indicate whether blueprint can be requested from any project in the organization that entity belongs to.
	// Flag to indicate blueprint can be requested from any project in org
	RequestScopeOrg *bool `json:"requestScopeOrg,omitempty" tf:"request_scope_org,omitempty"`
}

type BlueprintObservation struct {

	// Blueprint YAML content.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// ID of content source.
	ContentSourceID *string `json:"contentSourceId,omitempty" tf:"content_source_id,omitempty"`

	// Content source path.
	ContentSourcePath *string `json:"contentSourcePath,omitempty" tf:"content_source_path,omitempty"`

	// Date when content source was last synced. The date is in ISO 8601 and UTC.
	ContentSourceSyncAt *string `json:"contentSourceSyncAt,omitempty" tf:"content_source_sync_at,omitempty"`

	// Content source last sync messages.
	// +listType=set
	ContentSourceSyncMessages []*string `json:"contentSourceSyncMessages,omitempty" tf:"content_source_sync_messages,omitempty"`

	// Content source last sync status. Supported values: SUCCESSFUL, FAILED.
	ContentSourceSyncStatus *string `json:"contentSourceSyncStatus,omitempty" tf:"content_source_sync_status,omitempty"`

	// Content source type.
	ContentSourceType *string `json:"contentSourceType,omitempty" tf:"content_source_type,omitempty"`

	// Date when entity was created. The date is in ISO 8601 and UTC.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// The user who created entity.
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Human-friendly description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// ID of cloud template.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Human-friendly name used as an identifier in APIs that support this option.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of organization that entity belongs to.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// ID of project that entity belongs to.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Name of project that entity belongs to.
	ProjectName *string `json:"projectName,omitempty" tf:"project_name,omitempty"`

	// Flag to indicate whether blueprint can be requested from any project in the organization that entity belongs to.
	// Flag to indicate blueprint can be requested from any project in org
	RequestScopeOrg *bool `json:"requestScopeOrg,omitempty" tf:"request_scope_org,omitempty"`

	// HATEOAS of entity.
	SelfLink *string `json:"selfLink,omitempty" tf:"self_link,omitempty"`

	// Status of cloud template. Supported values: DRAFT, VERSIONED, RELEASED.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Total number of released versions.
	TotalReleasedVersions *float64 `json:"totalReleasedVersions,omitempty" tf:"total_released_versions,omitempty"`

	// Total number of versions.
	TotalVersions *float64 `json:"totalVersions,omitempty" tf:"total_versions,omitempty"`

	// Date when entity was last updated. Date and time format is ISO 8601 and UTC.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// The user who last updated the entity.
	UpdatedBy *string `json:"updatedBy,omitempty" tf:"updated_by,omitempty"`

	// Flag to indicate if the current content of the cloud template/blueprint is valid.
	Valid *bool `json:"valid,omitempty" tf:"valid,omitempty"`

	// List of validations messages.
	ValidationMessages []ValidationMessagesObservation `json:"validationMessages,omitempty" tf:"validation_messages,omitempty"`
}

type BlueprintParameters struct {

	// Blueprint YAML content.
	// +kubebuilder:validation:Optional
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// Human-friendly description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Human-friendly name used as an identifier in APIs that support this option.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of project that entity belongs to.
	// +crossplane:generate:reference:type=github.com/micgoe/provider-vmware-vra/apis/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// Flag to indicate whether blueprint can be requested from any project in the organization that entity belongs to.
	// Flag to indicate blueprint can be requested from any project in org
	// +kubebuilder:validation:Optional
	RequestScopeOrg *bool `json:"requestScopeOrg,omitempty" tf:"request_scope_org,omitempty"`
}

type ValidationMessagesInitParameters struct {
}

type ValidationMessagesObservation struct {
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// Human-friendly name used as an identifier in APIs that support this option.
	ResourceName *string `json:"resourceName,omitempty" tf:"resource_name,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ValidationMessagesParameters struct {
}

// BlueprintSpec defines the desired state of Blueprint
type BlueprintSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BlueprintParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BlueprintInitParameters `json:"initProvider,omitempty"`
}

// BlueprintStatus defines the observed state of Blueprint.
type BlueprintStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BlueprintObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Blueprint is the Schema for the Blueprints API. A resource that can be used to create a vRealize Automation cloud template, formerly know as blueprint.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vmware-vra}
type Blueprint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   BlueprintSpec   `json:"spec"`
	Status BlueprintStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BlueprintList contains a list of Blueprints
type BlueprintList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Blueprint `json:"items"`
}

// Repository type metadata.
var (
	Blueprint_Kind             = "Blueprint"
	Blueprint_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Blueprint_Kind}.String()
	Blueprint_KindAPIVersion   = Blueprint_Kind + "." + CRDGroupVersion.String()
	Blueprint_GroupVersionKind = CRDGroupVersion.WithKind(Blueprint_Kind)
)

func init() {
	SchemeBuilder.Register(&Blueprint{}, &BlueprintList{})
}
