apiVersion: blueprint.micgoe.io/v1alpha1
kind: Version
metadata:
  annotations:
    meta.upbound.io/example-id: blueprint/v1alpha1/version
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    blueprintIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    changeLog: First version
    description: Released from vRA terraform provider
    release: true
    version: ${(random_integer.suffix.result / random_integer.suffix.result)}
