apiVersion: fabric.micgoe.io/v1alpha1
kind: DatastoreVsphere
metadata:
  annotations:
    meta.upbound.io/example-id: fabric/v1alpha1/datastorevsphere
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    tags:
    - key: foo
      value: bar
