// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AccountVsphereInitParameters struct {

	// Accept self-signed certificate when connecting to the cloud account.
	// Whether to accept self signed certificate when connecting to the vCenter Server.
	AcceptSelfSignedCert *bool `json:"acceptSelfSignedCert,omitempty" tf:"accept_self_signed_cert,omitempty"`

	// Cloud accounts associated with the cloud account.
	// NSX-V or NSX-T account ids to associate with this vSphere cloud account.
	// +listType=set
	AssociatedCloudAccountIds []*string `json:"associatedCloudAccountIds,omitempty" tf:"associated_cloud_account_ids,omitempty"`

	// Identifier of a data collector VM deployed in the on premise infrastructure.
	// Identifier of a data collector vm deployed in the on premise infrastructure.
	DcID *string `json:"dcId,omitempty" tf:"dc_id,omitempty"`

	// Human-friendly description.
	// A human-friendly description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// IP address or FQDN of the vCenter Server. The cloud proxy belongs on this vCenter.
	// IP address or FQDN of the vCenter Server.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Name of the vSphere cloud account.
	// The name of this resource instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Password used to authenticate to the cloud account.
	// Password of the vCenter Server.
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// A set of region names that are enabled for the cloud account.
	// The set of region ids that will be enabled for this cloud account.
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// A set of tag keys and optional values to apply to the cloud account.
	// Example: [ { "key" : "vmware", "value": "provider" } ]
	Tags []AccountVsphereTagsInitParameters `json:"tags,omitempty" tf:"tags,omitempty"`

	// vSphere username used to authenticate to the cloud account.
	// Username of the vCenter Server.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type AccountVsphereLinksInitParameters struct {
}

type AccountVsphereLinksObservation struct {
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	// +listType=set
	Hrefs []*string `json:"hrefs,omitempty" tf:"hrefs,omitempty"`

	Rel *string `json:"rel,omitempty" tf:"rel,omitempty"`
}

type AccountVsphereLinksParameters struct {
}

type AccountVsphereObservation struct {

	// Accept self-signed certificate when connecting to the cloud account.
	// Whether to accept self signed certificate when connecting to the vCenter Server.
	AcceptSelfSignedCert *bool `json:"acceptSelfSignedCert,omitempty" tf:"accept_self_signed_cert,omitempty"`

	// Cloud accounts associated with the cloud account.
	// NSX-V or NSX-T account ids to associate with this vSphere cloud account.
	// +listType=set
	AssociatedCloudAccountIds []*string `json:"associatedCloudAccountIds,omitempty" tf:"associated_cloud_account_ids,omitempty"`

	// Date when  entity was created. Date and time format is ISO 8601 and UTC.
	// Date when the entity was created. The date is in ISO 8601 and UTC.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Identifier of a data collector VM deployed in the on premise infrastructure.
	// Identifier of a data collector vm deployed in the on premise infrastructure.
	DcID *string `json:"dcId,omitempty" tf:"dc_id,omitempty"`

	// Human-friendly description.
	// A human-friendly description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// IP address or FQDN of the vCenter Server. The cloud proxy belongs on this vCenter.
	// IP address or FQDN of the vCenter Server.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// ID of the vSphere cloud account.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// HATEOAS of entity.
	Links []AccountVsphereLinksObservation `json:"links,omitempty" tf:"links,omitempty"`

	// Name of the vSphere cloud account.
	// The name of this resource instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of organization that entity belongs to.
	// The id of the organization this entity belongs to.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Email of entity owner.
	// Email of the user that owns the entity.
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// A set of region names that are enabled for the cloud account.
	// The set of region ids that will be enabled for this cloud account.
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// A set of tag keys and optional values to apply to the cloud account.
	// Example: [ { "key" : "vmware", "value": "provider" } ]
	Tags []AccountVsphereTagsObservation `json:"tags,omitempty" tf:"tags,omitempty"`

	// Date when the entity was last updated. Date and time format is ISO 8601 and UTC.
	// Date when the entity was last updated. The date is ISO 8601 and UTC.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// vSphere username used to authenticate to the cloud account.
	// Username of the vCenter Server.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type AccountVsphereParameters struct {

	// Accept self-signed certificate when connecting to the cloud account.
	// Whether to accept self signed certificate when connecting to the vCenter Server.
	// +kubebuilder:validation:Optional
	AcceptSelfSignedCert *bool `json:"acceptSelfSignedCert,omitempty" tf:"accept_self_signed_cert,omitempty"`

	// Cloud accounts associated with the cloud account.
	// NSX-V or NSX-T account ids to associate with this vSphere cloud account.
	// +kubebuilder:validation:Optional
	// +listType=set
	AssociatedCloudAccountIds []*string `json:"associatedCloudAccountIds,omitempty" tf:"associated_cloud_account_ids,omitempty"`

	// Identifier of a data collector VM deployed in the on premise infrastructure.
	// Identifier of a data collector vm deployed in the on premise infrastructure.
	// +kubebuilder:validation:Optional
	DcID *string `json:"dcId,omitempty" tf:"dc_id,omitempty"`

	// Human-friendly description.
	// A human-friendly description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// IP address or FQDN of the vCenter Server. The cloud proxy belongs on this vCenter.
	// IP address or FQDN of the vCenter Server.
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Name of the vSphere cloud account.
	// The name of this resource instance.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Password used to authenticate to the cloud account.
	// Password of the vCenter Server.
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// A set of region names that are enabled for the cloud account.
	// The set of region ids that will be enabled for this cloud account.
	// +kubebuilder:validation:Optional
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// A set of tag keys and optional values to apply to the cloud account.
	// Example: [ { "key" : "vmware", "value": "provider" } ]
	// +kubebuilder:validation:Optional
	Tags []AccountVsphereTagsParameters `json:"tags,omitempty" tf:"tags,omitempty"`

	// vSphere username used to authenticate to the cloud account.
	// Username of the vCenter Server.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type AccountVsphereTagsInitParameters struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type AccountVsphereTagsObservation struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type AccountVsphereTagsParameters struct {

	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

// AccountVsphereSpec defines the desired state of AccountVsphere
type AccountVsphereSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AccountVsphereParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccountVsphereInitParameters `json:"initProvider,omitempty"`
}

// AccountVsphereStatus defines the observed state of AccountVsphere.
type AccountVsphereStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccountVsphereObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccountVsphere is the Schema for the AccountVspheres API. Creates a vra_cloud_account_vsphere resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vmware-vra}
type AccountVsphere struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.hostname) || (has(self.initProvider) && has(self.initProvider.hostname))",message="spec.forProvider.hostname is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.regions) || (has(self.initProvider) && has(self.initProvider.regions))",message="spec.forProvider.regions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   AccountVsphereSpec   `json:"spec"`
	Status AccountVsphereStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountVsphereList contains a list of AccountVspheres
type AccountVsphereList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountVsphere `json:"items"`
}

// Repository type metadata.
var (
	AccountVsphere_Kind             = "AccountVsphere"
	AccountVsphere_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountVsphere_Kind}.String()
	AccountVsphere_KindAPIVersion   = AccountVsphere_Kind + "." + CRDGroupVersion.String()
	AccountVsphere_GroupVersionKind = CRDGroupVersion.WithKind(AccountVsphere_Kind)
)

func init() {
	SchemeBuilder.Register(&AccountVsphere{}, &AccountVsphereList{})
}
